name: this is a test2 action

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/test2.yml"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: test
        run: |
          echo this is a test action
          gh workflow list
          # gh run cancel ${{ github.run_id}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


