name: this is a test action

on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: touch job1
        run: |
          touch job1
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: job1
          path: ./
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: touch job2
        run: |
          touch job2
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: job2
          path: ./
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          path: ./job3

      - name: list file
        run: |
          ls -R
