name: this is a test1 action

on:
  push:
    paths:
      - ".github/workflows/test1.yml"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check if file exists
        run: |
          if [ ! -f "aaa.txt" ]; then
            echo "File does not exist, skipping remaining steps"
            cancelled()
          fi
      - name: Step 1
        run: echo "This is step 1"
      - name: Step 2
        run: echo "This is step 2"
    

