name: this is a test action

on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: touch job1
        run: |
          touch job1
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: touch job2
        run: |
          touch job2
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: list file
        run: |
          ls -al