name: this is a uros action

on:
  push:
    paths:
      - ".github/workflows/uros.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kaylor/microros_base:humble
    defaults:
      run:
        shell: bash
    steps:
      - name: build test
        run: |
          pwd
          ls -al
          cd /uros_ws
          ros2 run micro_ros_setup build_firmware.sh