name: this is a uros action

on:
  push:
    paths:
      - ".github/workflows/uros.yml"
jobs:
  job1:
    runs-on: kaylor/microros_base:humble
    steps:
      - name: build test
        run: |
          pwd
          ls -al
          cd /uros_ws
          ros2 run micro_ros_setup build_firmware.sh